### ISSUE TITLE
High memory consumption in macOS on version 3.0

### ISSUE THREAD

**Issue by Ponny035** [TanametTpk/gameOutSideGame#5]
When run with higher than low graphical setting game suddenly stop working and  follow by whole macOS system lacking to the point that unusable.  

##  Mac Specifically:

- MacBook Pro 15" 2017
- i7 
- 16 GB of RAM
- Radeon Pro 555 2 GB
- OS macOS version : 12.3.1

**Comment by TanametTpk** [comment]
I just reupload game that removed effect, And added limit frame rate.
Then I'm test game on my 13-inch MacBook Pro 2020 (not M1).
Now it should be playable.
